FROM registry.redhat.io/jboss-eap-7/eap-xp4-openjdk11-openshift-rhel8:4.0-18.1652296007

USER 185
# COPY configuration /opt/eap/bin
COPY configuration/standalone-openshift.xml /opt/eap/standalone/configuration/standalone-openshift.xml

CMD [ "/opt/eap/bin/openshift-launch.sh" ]